# Generated by Django 3.0.8 on 2020-08-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200811_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
