# Generated by Django 3.0.8 on 2020-08-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200811_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='answer_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='question_count',
        ),
    ]
