# Generated by Django 3.0.8 on 2020-08-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200812_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
    ]
