# Generated by Django 2.2.15 on 2020-08-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200823_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lol',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
