# Generated by Django 2.2.15 on 2020-08-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_user_lol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lol',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
