# Generated by Django 2.2.15 on 2020-08-25 08:49

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200824_1427'),
    ]

    operations = [
    	TrigramExtension()
    ]
